.circleci/config.yml, package.json
Build, lint, and test on CircleCI.
`None`
=> Integrate CI using CircleCI

.eslintignore, config/custom-environment-variables.json, config/testing.json, package-lock.json, package.json, src/modules/logger/internals/console-logger.ts, src/modules/logger/internals/loggers.ts, src/modules/logger/internals/rollbar-logger.ts, src/modules/logger/internals/types.ts, src/modules/logger/logger-manager.ts, src/modules/logger/logger.ts, src/modules/logger/types.ts, test/spec/logger/logger.spec.ts
Logger service - log to console for local and testing env, log to rollbar for staging, qa, beta and production.
`None`
- Loggers should initialize
- Log to rollbar
- Log to console
=> logger service

src/main.ts, src/modules/access-token/access-token-service.ts, src/modules/access-token/internal/access-token-writer.ts, src/modules/access-token/rest-api/access-token-controller.ts, src/modules/access-token/rest-api/access-token-rest-api-server.ts, src/modules/access-token/rest-api/access-token-router.ts, src/modules/access-token/types.ts, test/spec/access-token/access-token.spec.ts
Update access token params
`None`
- POST /access-tokens should return access token for given username password
- User should be able to log in
=> access token params

src/modules/communication/internals/sendgrid-service.ts, src/modules/communication/internals/twilio-service.ts
We were logging all third party errors in the communication microservice, but we need to only get notified about certain important cases, so we are now logging only necessary third party errors.
NA
NA
NA
=> Logging necessary third party errors in communication microservice

config/custom-environment-variables.yml, config/default.yml, config/development.yml, config/e2e.yml, config/preview.yml, config/production.yml, config/staging.yml, config/testing.yml, package-lock.json, package.json, src/app.ts, src/modules/logger/internals/grafana-loki-logger.ts, src/modules/logger/internals/loggers.ts, src/modules/logger/internals/types.ts, src/modules/logger/internals/winston-logger.ts, src/modules/logger/internals/winston-transport.ts, src/modules/logger/logger-manager.ts
- Added support for logging via Grafana using Loki
- NA
- NA
- NA
=> PT-46: Add support for logging via Grafana using Loki

README.md, terraform/main.tf, terraform/modules/digital-ocean/cluster.tf, terraform/variables.tf
- Added support for creating CPU alert
- Added support for creating Memory alert
- NA
- NA
- NA
=> PT-49: Add support for Memory / CPU usage alert for K8 workers

src/modules/config/config-service.ts, test/spec/config/config.spec.ts
Updated `ConfigService`, added `hasValue` for checking config existence
- NA
- NA
- NA
=> Feat: Add support for checking config value exsitence

.github/workflows/clean_on_delete.yml, .github/workflows/clean_on_dispatch.yml, .github/workflows/clean_on_pr_closed.yml, .github/workflows/preview_on_dispatch.yml, .github/workflows/preview_on_pr_update.yml, .github/workflows/production_on_push.yml, README.md
- Migrated workflows to v2.3
- Added concurrency to workflows
- Updated documentation
- NA
- NA
- NA
=> Migrate workflows to v2.3

config/development.yml, cypress/e2e/app.spec.cy.ts, lib/kube/shared/deployment.yaml, src/apps/frontend/app.component.tsx, src/apps/frontend/index.html, src/apps/frontend/pages/index.ts, src/apps/frontend/pages/not-found/not-found.page.tsx
- Fixed issue where app returned 404 when using url with params
- NA
- NA
- NA
=> Fixed issue where using path with params returned 404 Not Found

.github/workflows/clean_on_delete.yml, .github/workflows/clean_on_dispatch.yml, .github/workflows/clean_on_pr_closed.yml, .github/workflows/preview_on_dispatch.yml, .github/workflows/preview_on_pr_update.yml, .github/workflows/production_on_push.yml, README.md
- See CHANGELOG for what's changed in v2.4 - https://github.com/jalantechnologies/platform-github/pull/6
- NA
- NA
- NA
=> Migrate workflows to v2.4

.github/workflows/production_on_push.yml
_A few sentences describing the overall goals of the pull request's commits. In case you are creating or updating new endpoints, please document request, response schema._
_Please document any change in database schema made part of this PR._
- _Description of automated test 1_
- _Description of automated test 2_
- _Description of automated test 3_
- _Description of manual test 1_
- _Description of manual test 2_
- _Description of manual test 3_
=> Switching production deployments to Render

.github/workflows/clean_on_delete.yml, .github/workflows/clean_on_dispatch.yml, .github/workflows/clean_on_pr_closed.yml, .github/workflows/preview_on_dispatch.yml, .github/workflows/preview_on_pr_update.yml, .github/workflows/production_on_push.yml
- This bumps CI version to [v1.3.1](https://github.com/jalantechnologies/github-ci/releases/tag/v1.3.1)
- NA
- NA
- NA
=> Bump CI version to v1.3.1

config/custom-environment-variables.yml, config/preview.yml, config/production.yml, lib/kube/shared/deployment.yaml, package-lock.json, package.json, src/apps/backend/modules/logger/internals/loggers.ts, src/apps/backend/modules/logger/internals/papertrail-logger.ts, src/apps/backend/modules/logger/internals/types.ts
- This adds support for logging via papertrail
- NA
- NA
- NA
=> (feat) Add support for logging via Papertrail 

docker-compose.dev.yml
Fixed bug in building and running docker container on development env
NA
NA
run command - docker compose -f docker-compose.dev.yml up and docker container should be up and running
=> Fixed bug in docker compose on development env

.github/workflows/preview_on_pr_update.yml
_A few sentences describing the overall goals of the pull request's commits. In case you are creating or updating new endpoints, please document request, response schema._
_Please document any change in database schema made part of this PR._
- _Description of automated test 1_
- _Description of automated test 2_
- _Description of automated test 3_
- _Description of manual test 1_
- _Description of manual test 2_
- _Description of manual test 3_
=> test: Trying out multiple build cache sources

.github/workflows/preview_on_pr_update.yml, .github/workflows/production_on_push.yml
_A few sentences describing the overall goals of the pull request's commits. In case you are creating or updating new endpoints, please document request, response schema._
_Please document any change in database schema made part of this PR._
- _Description of automated test 1_
- _Description of automated test 2_
- _Description of automated test 3_
- _Description of manual test 1_
- _Description of manual test 2_
- _Description of manual test 3_
=> test: Trying out multiple build cache sources (2)

.github/workflows/clean_on_delete.yml, .github/workflows/clean_on_dispatch.yml, .github/workflows/clean_on_pr_closed.yml, .github/workflows/preview_on_dispatch.yml, .github/workflows/preview_on_pr_update.yml, .github/workflows/production_on_push.yml
- This bumps CI version to v1.4
- NA
- NA
- NA
=> Bump CI version to v1.4

src/apps/backend/modules/application/application-repository.ts
Issue:
In our MongoDB development, removing indexes from the code doesn't synchronize with the database, leading to unused indexes accumulating and impacting query efficiency. We need an automated solution to detect and remove these unused indexes to ensure database performance and integrity.
check: https://mongoosejs.com/docs/api/model.html#Model.syncIndexes()
also: https://thecodebarbarian.com/whats-new-in-mongoose-5-2-syncindexes#:~:text=Model.syncIndexes()-,The%20Model.,on%20the%20collection%20in%20MongoDB.
NA
- _NA
=> Improved Index Management in MongoDB

src/apps/backend/modules/account/account-service.ts, src/apps/backend/modules/account/internal/account-writer.ts, src/apps/backend/modules/account/rest-api/account-controller.ts, src/apps/backend/modules/account/rest-api/account-router.ts, src/apps/backend/modules/account/types.ts, test/spec/account/account.spec.ts
_This PR is introduced to add the feature of updating account details._
_NA_
- _PATCH /accounts/:accountId_
- should update account details
- should throw 404 if account does not exist
- _Checked using postman if account details are updating._
- _Checked if Reset Password Functionality is working as it is from frontend._
https://github.com/jalantechnologies/boilerplate-mern/assets/128154648/70ac8bcd-3d60-48c2-bd74-0b4500e69409
=> Feat: Add "Update Account Details" support

.github/workflows/clean_on_delete.yml, .github/workflows/clean_on_dispatch.yml, .github/workflows/clean_on_pr_closed.yml, .github/workflows/preview_on_dispatch.yml, .github/workflows/preview_on_pr_update.yml, .github/workflows/production_on_push.yml, lib/kube/preview/deployment.yaml, lib/kube/production/deployment.yaml
This makes following updates:
- This updates the workflow versions to `v2.2`
- This adds affinity to deployments based on node pool selectors
- This adds priority to preview deployments
- NA
- NA
- NA
=> chore: Project deployment updates

docker-compose.dev.yml
Hot reload server running inside docker container upon file change
- Made sure that the node_modules folder should not get mounted, and the folder inside container and host machine should remain unsycned
=> bug-fix: Hot reload server inside docker container upon file change

.github/workflows/preview_on_pr_update.yml, sonar-project.properties
- This closes - https://github.com/jalantechnologies/boilerplate-mern/issues/138
- Can ignore the analysis check failure - It needs to run on `main` first
- NA
- NA
- NA
=> fix: Duplicated code amongst apps (frontend and backend) fails SonarQube check

config/production.yml
_To temporarily add support for deafult OTP for creating/logging account._
NA
NA
NA
=> Feat: Add support for default OTP

README.md
- This updates the README and removes links to expired documentation
- NA
- NA
- NA
=> chore: remove expired deployment doc from README

.github/workflows/clean_on_delete.yml, .github/workflows/clean_on_dispatch.yml, .github/workflows/clean_on_pr_closed.yml, .github/workflows/preview_on_dispatch.yml, .github/workflows/preview_on_pr_update.yml, .github/workflows/production_on_push.yml
- This updates workflows to v2.4 to address the "docker-compose: command not found" issue
- NA
- NA
- NA
=> chore: Update workflows to v2.4

.github/workflows/clean_on_delete.yml, .github/workflows/clean_on_dispatch.yml, .github/workflows/clean_on_pr_closed.yml, .github/workflows/preview_on_dispatch.yml, .github/workflows/preview_on_pr_update.yml, .github/workflows/production_on_push.yml
_This PR updates the workflow version from `2.4` to `2.5`._
NA
NA
NA
=> chore: Update workflows to v2.5

.husky/pre-commit, lint-staged.config.js, package-lock.json, package.json
Added `lint-staged` - https://github.com/jalantechnologies/rflask-boilerplate/pull/107#issuecomment-2607222687
_Reopen #192 due to CI failure_
Resolves #191 
- I made changes to a couple of files and made a dummy commit, the file which was staged got formatted and added to the commit and the other file was left unchanged.
=> feat: add lint-staged

package-lock.json, package.json
Upgraded `bcrypt` to version `5.1.0` | Resolves #210 
Ran `npm ci` and ensured the modules are installed without errors.
=> fix: bcrypt installation issue

cypress/e2e/login.spec.cy.ts, test/fixtures/accounts.ts
Resolved issues with cypress e2e tests - the login tests are fixed now as well as the test suite now fails if a single test is failing (refer test videos below) | Resolves #107 
https://github.com/user-attachments/assets/4665d919-849f-469e-a169-0d051e4f7e8c
https://github.com/user-attachments/assets/1f7ef04f-3d42-47dc-8422-3720cebaf5b0
=> fix: resolve issues with cypress e2e tests

src/apps/backend/modules/application/application-repository.ts
Implement MongoDB connection caching | Resolves #231
=> feat: implement mongodb connection caching
